/* eslint-disable */
// This file is auto-generated by scripts/generate-lut-matrices.mjs
// Do not edit manually.

import { ColorMatrix4x5 } from "../types/pipeline";

export interface GeneratedLutMatrix {
  sourceFile: string;
  sourceSha256: string;
  lutSize: number;
  rmse: [number, number, number];
  colorMatrix: [number, number, number, number, number, number, number, number, number];
  colorMatrix4x5: ColorMatrix4x5;
}

export const GENERATED_LUT_MATRICES: Partial<Record<"VTG1" | "VTG2", GeneratedLutMatrix>> = {
  VTG1: {
    sourceFile: "assets/luts/vintage1.cube",
    sourceSha256: "0d92b283fab0eca88f99c86a1d4a3c069b8ebe5bf2cc56f3b4ebf4f3ca0e7f6b",
    lutSize: 16,
    rmse: [0.029974, 0.085614, 0.039657],
    colorMatrix: [1.038975, -0.00168, -0.001115, -0.00102, 1.219433, -0.012941, -0.00073, -0.008335, 0.967811],
    colorMatrix4x5: [1.038975, -0.00168, -0.001115, 0, -12.5792, -0.00102, 1.219433, -0.012941, 0, -42.1249, -0.00073, -0.008335, 0.967811, 0, -14.5143, 0, 0, 0, 1, 0]
  },
  VTG2: {
    sourceFile: "assets/luts/vintage2.cube",
    sourceSha256: "5ace10b37d8bf512e5fa7f76076e8737d6868640e97785ddaa1010886fb84296",
    lutSize: 16,
    rmse: [0.033612, 0.107912, 0.028431],
    colorMatrix: [1.0433, -0.003517, -0.006244, -0.000772, 1.207984, -0.02262, -0.001661, -0.014208, 0.915059],
    colorMatrix4x5: [1.0433, -0.003517, -0.006244, 0, 14.4916, -0.000772, 1.207984, -0.02262, 0, -28.9363, -0.001661, -0.014208, 0.915059, 0, 10.2147, 0, 0, 0, 1, 0]
  },
};

